#test
test:
  path: /test
  controller: App\Controller\TestController::test

#index
index:
  path: /
  controller: App\Controller\DefaultController::index

#Api
api:
  path: /api/http
  controller: App\Controller\HttpController::createRequest
  methods: POST

